# Dependencies
markdown:            kramdown
highlighter:         rouge

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:            JuliaKM
tagline:          'Julia Kulla-Mader&#39;s Home on the Interweb'
description:      'You can also find me <a href="https://www.facebook.com/JuliaKM">other</a> <a href="http://www.linkedin.com/in/juliakm/">places</a>.'
url:              http://juliakm.github.io
baseurl:          /

author:
  name:           'Julia K-M'
  url:            https://twitter.com/JuliaKM

paginate:         5

# About/contact
author:
  name:              JuliaKM
  url:               https://twitter.com/juliakm
  email:             jkullama@gmail.com

# Custom vars
version:             1.0.0

gems:
  - jekyll-redirect-from
